In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import seaborn as sns

In [2]:
from sklearn.datasets import fetch_california_housing

In [5]:
data = fetch_california_housing()

In [7]:
data.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [23]:
data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [19]:
data.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [21]:
data.target_names

['MedHouseVal']

In [11]:
data2 = pd.DataFrame(data.data, columns=data.feature_names)
type(data2)

pandas.core.frame.DataFrame

In [13]:
data2

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [50]:
missing_values = data_1.isnull().sum()
print("Missing values in each column:")
print(missing_values)

Missing values in each column:
MedInc        0
HouseAge      0
Population    0
Latitude      0
Longitude     0
dtype: int64


In [52]:
data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   Population  20640 non-null  float64
 3   Latitude    20640 non-null  float64
 4   Longitude   20640 non-null  float64
dtypes: float64(5)
memory usage: 806.4 KB


In [54]:
data_1.describe()

MedInc      HouseAge    Population      Latitude     Longitude
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000
mean       3.870671     28.639486   1425.476744     35.631861   -119.569704
std        1.899822     12.585558   1132.462122      2.135952      2.003532
min        0.499900      1.000000      3.000000     32.540000   -124.350000
25%        2.563400     18.000000    787.000000     33.930000   -121.800000
50%        3.534800     29.000000   1166.000000     34.260000   -118.490000
75%        4.743250     37.000000   1725.000000     37.710000   -118.010000
max       15.000100     52.000000  35682.000000     41.950000   -114.310000

In [56]:
from sklearn.preprocessing import StandardScaler

In [58]:
scaleStandard = StandardScaler()

In [64]:
data_1 = scaleStandard.fit_transform(data_1)

In [ ]:
data_1 = pd.DataFrame(data_1, columns = ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms',	'Population','AveOccup','Latitude','Longitude'])	

In [68]:
data2

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [80]:
from sklearn.preprocessing import MinMaxScaler

In [82]:
ScaleMinMax = MinMaxScaler(feature_range=(0,1))

In [88]:
data2 = ScaleMinMax.fit_transform(data2)

In [90]:
data2 = pd.DataFrame(data2, columns = ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms',	'Population','AveOccup','Latitude','Longitude'])
data2

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
0      0.539668  0.784314  0.043512   0.020469    0.008941  0.001499   
1      0.538027  0.392157  0.038224   0.018929    0.067210  0.001141   
2      0.466028  1.000000  0.052756   0.021940    0.013818  0.001698   
3      0.354699  1.000000  0.035241   0.021929    0.015555  0.001493   
4      0.230776  1.000000  0.038534   0.022166    0.015752  0.001198   
...         ...       ...       ...        ...         ...       ...   
20635  0.073130  0.470588  0.029769   0.023715    0.023599  0.001503   
20636  0.141853  0.333333  0.037344   0.029124    0.009894  0.001956   
20637  0.082764  0.313725  0.030904   0.023323    0.028140  0.001314   
20638  0.094295  0.333333  0.031783   0.024859    0.020684  0.001152   
20639  0.130253  0.294118  0.031252   0.024573    0.038790  0.001549   

       Latitude  Longitude  
0      0.567481   0.211155  
1      0.565356   0.212151  
2      0.564293   0.210159  
3      0.564293   0.209163  
4      0.564293   0.209163  
...         ...        ...  
20635  0.737513   0.324701  
20636  0.738576   0.312749  
20637  0.732200   0.311753  
20638  0.732200   0.301793  
20639  0.725824   0.309761  

[20640 rows x 8 columns]

In [15]:
from sklearn.linear_model import LinearRegression

In [17]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [75]:
x = data2[['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population','AveOccup','Latitude']]
y = data2['Longitude']

In [29]:
model = LinearRegression()

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [31]:
model.fit(X_train,y_train)

LinearRegression()

In [35]:
Y_predict = model.predict(X_test)

In [37]:
Y_predict

array([-119.64996293, -119.02610127, -122.16381508, ..., -121.6613233 ,
       -120.44277427, -118.30580105])

In [39]:
y_test

20046   -119.01
3024    -119.46
15663   -122.44
20484   -118.72
9814    -121.93
          ...  
15362   -117.22
16623   -120.83
18086   -122.05
2144    -119.76
3665    -118.37
Name: Longitude, Length: 4128, dtype: float64

In [41]:
print("Mean Squared Error (MSE):", mean_squared_error(y_test, Y_predict))

Mean Squared Error (MSE): 0.42701998092820287


In [43]:
print("R-Squared Error (RSE):", r2_score(y_test, Y_predict))

R-Squared Error (RSE): 0.8926261623108509


In [45]:
print("Mean Absolute Error (MAE):", mean_absolute_error(y_test, Y_predict))

Mean Absolute Error (MAE): 0.48148712973257185
